using ChatServer.Services;
using Microsoft.AspNetCore.Mvc;
using System;
using ChatClient.Shared.Models; // For client-facing DTO
using ChatServer.Models; // For server-side model

namespace ChatServer.Controllers
{
    [ApiController]
    [Route("[controller]")]
    public class MessagesController : ControllerBase
    {
        private readonly IMessageBrokerService _messageBrokerService;
        private readonly WebSocketHandler _webSocketHandler;

        public MessagesController(IMessageBrokerService messageBrokerService, WebSocketHandler webSocketHandler)
        {
            _messageBrokerService = messageBrokerService;
            _webSocketHandler = webSocketHandler;
        }

        [HttpPost("send")]
        public async Task<IActionResult> SendMessage(ChatClient.Shared.Models.Message clientMessage)
        {
            try
            {
                var serverMessage = new ChatServer.Models.Message
                {
                    ChatId = clientMessage.ChatId,
                    SenderId = clientMessage.SenderId,
                    Content = clientMessage.Content,
                    // Id and DeliveryId will be generated by the server/database
                    Timestamp = DateTime.UtcNow, // Use current server time
                    // Files = clientMessage.Files // Need to handle file conversion if applicable
                };
                await _messageBrokerService.SendMessage(serverMessage);
                
                // Notify via WebSocket
                var wsMessage = new
                {
                    Id = serverMessage.Id,
                    ChatId = serverMessage.ChatId,
                    SenderId = serverMessage.SenderId,
                    Content = serverMessage.Content,
                    DeliveryId = serverMessage.Id,
                    Timestamp = serverMessage.Timestamp
                };
                _ = WebSocketHandler.NotifyNewMessageAsync(serverMessage.ChatId, wsMessage);
                
                return Ok();
            }
            catch (Exception ex)
            {
                return BadRequest(new { message = ex.Message });
            }
        }

        [HttpGet("receive")]
        public async Task<IActionResult> ReceiveMessage(int chatId, long lastDeliveryId)
        {
            try
            {
                var serverMessage = await _messageBrokerService.ReceiveMessage(chatId, lastDeliveryId);
                if (serverMessage != null)
                {
                    var clientMessage = new ChatClient.Shared.Models.Message
                    {
                        Id = serverMessage.Id,
                        ChatId = serverMessage.ChatId,
                        SenderId = serverMessage.SenderId,
                        Content = serverMessage.Content,
                        DeliveryId = serverMessage.Id, // Use server message Id as DeliveryId
                        Timestamp = serverMessage.Timestamp // Convert DateTime to DateTimeOffset if needed on client
                    };
                    return Ok(clientMessage);
                }
                return Ok(null);
            }
            catch (Exception ex)
            {
                return BadRequest(new { message = ex.Message });
            }
        }

        [HttpGet("history")]
        public async Task<IActionResult> GetChatHistory(int chatId)
        {
            try
            {
                var serverMessages = await _messageBrokerService.GetChatHistory(chatId);
                var clientMessages = new List<ChatClient.Shared.Models.Message>();
                foreach (var serverMessage in serverMessages)
                {
                    clientMessages.Add(new ChatClient.Shared.Models.Message
                    {
                        Id = serverMessage.Id,
                        ChatId = serverMessage.ChatId,
                        SenderId = serverMessage.SenderId,
                        Content = serverMessage.Content,
                        DeliveryId = serverMessage.Id, // Use server message Id as DeliveryId
                        Timestamp = serverMessage.Timestamp // Convert DateTime to DateTimeOffset if needed on client
                    });
                }
                return Ok(clientMessages);
            }
            catch (Exception ex)
            {
                return BadRequest(new { message = ex.Message });
            }
        }
    }
}
